from __future__ import annotations

import json
from pathlib import Path

from jinja2 import Template

from hipaa_audit.models import AuditReport, CheckStatus

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>HIPAA Compliance Dashboard — {{ org_name }}</title>
  <style>
    :root { --pass:#0d7a4a; --fail:#b42318; --warn:#b54708; --manual:#475467; --bg:#f8fafc; }
    body { font-family: system-ui, sans-serif; margin: 0; background: var(--bg); color: #101828; }
    header { background: #0c6e7c; color: white; padding: 1.5rem 2rem; }
    header h1 { margin: 0; font-size: 1.5rem; }
    .meta { opacity: .9; font-size: .9rem; margin-top: .5rem; }
    .summary { display: flex; gap: 1rem; padding: 1.5rem 2rem; flex-wrap: wrap; }
    .card { background: white; border-radius: 8px; padding: 1rem 1.25rem; min-width: 120px;
            box-shadow: 0 1px 3px rgba(0,0,0,.08); }
    .card strong { font-size: 1.75rem; display: block; }
    .pass strong { color: var(--pass); }
    .fail strong { color: var(--fail); }
    .warn strong { color: var(--warn); }
    .manual strong { color: var(--manual); }
    main { padding: 0 2rem 2rem; }
    table { width: 100%; border-collapse: collapse; background: white; border-radius: 8px;
             overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,.08); }
    th, td { text-align: left; padding: .75rem 1rem; border-bottom: 1px solid #eaecf0; }
    th { background: #f2f4f7; font-size: .85rem; text-transform: uppercase; letter-spacing: .03em; }
    .badge { display: inline-block; padding: .2rem .5rem; border-radius: 4px; font-size: .75rem;
             font-weight: 600; text-transform: uppercase; }
    .badge.pass { background: #dcfae6; color: var(--pass); }
    .badge.fail { background: #fee4e2; color: var(--fail); }
    .badge.warn { background: #fef0c7; color: var(--warn); }
    .badge.manual { background: #f2f4f7; color: var(--manual); }
    .badge.skip { background: #f9fafb; color: #98a2b3; }
    .citation { font-size: .8rem; color: #667085; }
    footer { padding: 1rem 2rem; font-size: .8rem; color: #667085; }
  </style>
</head>
<body>
  <header>
    <h1>HIPAA Security Rule — Compliance Dashboard</h1>
    <div class="meta">{{ org_name }} · {{ generated_at }} · {{ repo_path }}</div>
  </header>
  <div class="summary">
    <div class="card pass"><strong>{{ summary.pass }}</strong>Pass</div>
    <div class="card fail"><strong>{{ summary.fail }}</strong>Fail</div>
    <div class="card warn"><strong>{{ summary.warn }}</strong>Warn</div>
    <div class="card manual"><strong>{{ summary.manual }}</strong>Manual</div>
    <div class="card"><strong>{{ total }}</strong>Total controls</div>
    <div class="card"><strong>{{ score }}%</strong>Automated pass rate</div>
  </div>
  <main>
    <table>
      <thead>
        <tr><th>Control</th><th>Category</th><th>Citation</th><th>Status</th><th>Details</th></tr>
      </thead>
      <tbody>
        {% for row in rows %}
        <tr>
          <td><strong>{{ row.id }}</strong><br>{{ row.title }}</td>
          <td>{{ row.category }}</td>
          <td class="citation">{{ row.citation }}</td>
          <td><span class="badge {{ row.status }}">{{ row.status }}</span></td>
          <td>{{ row.message }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </main>
  <footer>
    Generated by <a href="https://github.com/jdawg555/hipaa-security-test">hipaa-audit</a> (open source).
    Not legal advice. Pair automated checks with annual SRA and counsel review.
  </footer>
</body>
</html>
"""


def write_reports(report: AuditReport, output_dir: Path) -> dict[str, Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    paths: dict[str, Path] = {}

    # JSON
    json_path = output_dir / "audit-report.json"
    payload = {
        "org_name": report.org_name,
        "generated_at": report.generated_at,
        "repo_path": report.repo_path,
        "summary": report.summary,
        "controls": [
            {
                "id": cr.control.id,
                "title": cr.control.title,
                "category": cr.control.category,
                "citation": cr.control.citation,
                "status": cr.status.value,
                "severity": cr.control.severity,
                "checks": [
                    {
                        "id": r.check_id,
                        "status": r.status.value,
                        "message": r.message,
                        "evidence_path": r.evidence_path,
                        "remediation": r.remediation,
                    }
                    for r in cr.results
                ],
            }
            for cr in report.controls
        ],
    }
    json_path.write_text(json.dumps(payload, indent=2))
    paths["json"] = json_path

    # Markdown
    md_path = output_dir / "audit-report.md"
    lines = [
        f"# HIPAA Audit Report — {report.org_name}",
        f"Generated: {report.generated_at}",
        "",
        "## Summary",
        "",
        "| Status | Count |",
        "|--------|-------|",
    ]
    for status, count in report.summary.items():
        if count:
            lines.append(f"| {status} | {count} |")
    lines.extend(["", "## Controls", ""])
    for cr in report.controls:
        lines.append(f"### {cr.control.id} — {cr.control.title}")
        lines.append(f"- **Citation:** {cr.control.citation}")
        lines.append(f"- **Status:** {cr.status.value}")
        for r in cr.results:
            lines.append(f"  - `{r.check_id}`: {r.status.value} — {r.message}")
        lines.append("")
    md_path.write_text("\n".join(lines))
    paths["markdown"] = md_path

    # HTML dashboard
    auto = [cr for cr in report.controls if cr.control.control_type.value != "manual"]
    auto_pass = sum(1 for cr in auto if cr.status == CheckStatus.PASS)
    score = int(100 * auto_pass / len(auto)) if auto else 0
    rows = []
    for cr in report.controls:
        msg = "; ".join(r.message for r in cr.results[:2])
        rows.append(
            {
                "id": cr.control.id,
                "title": cr.control.title,
                "category": cr.control.category,
                "citation": cr.control.citation,
                "status": cr.status.value,
                "message": msg[:200],
            }
        )
    html = Template(HTML_TEMPLATE).render(
        org_name=report.org_name,
        generated_at=report.generated_at,
        repo_path=report.repo_path,
        summary=report.summary,
        total=len(report.controls),
        score=score,
        rows=rows,
    )
    html_path = output_dir / "dashboard.html"
    html_path.write_text(html)
    paths["html"] = html_path

    return paths
