from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import yaml
from jinja2 import Template

TRUST_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% if public_url %}<link rel="canonical" href="{{ public_url }}">{% endif %}
  <title>Trust Center — {{ org_name }}</title>
  <style>
    :root { --accent:#0c6e7c; --muted:#667085; --bg:#f8fafc; --pass:#0d7a4a; }
    * { box-sizing: border-box; }
    body { font-family: system-ui, sans-serif; margin: 0; background: var(--bg); color: #101828; line-height: 1.5; }
    header { background: linear-gradient(135deg, var(--accent), #094b55); color: white; padding: 3rem 1.5rem; text-align: center; }
    header h1 { margin: 0 0 .5rem; font-size: 2rem; }
    header p { margin: 0; opacity: .92; max-width: 640px; margin-inline: auto; }
    main { max-width: 960px; margin: 0 auto; padding: 2rem 1.5rem 3rem; }
    .grid { display: grid; gap: 1.25rem; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); }
    .card { background: white; border-radius: 12px; padding: 1.25rem; box-shadow: 0 1px 3px rgba(0,0,0,.08); }
    .score { font-size: 2.5rem; font-weight: 700; color: var(--accent); }
    h2 { font-size: 1.15rem; margin: 2rem 0 1rem; }
    ul { padding-left: 1.2rem; }
    li { margin: .35rem 0; }
    .badge { display: inline-block; padding: .2rem .55rem; border-radius: 999px; font-size: .75rem; font-weight: 600; background: #e0f2f4; color: var(--accent); }
    .badge.implemented { background: #dcfae6; color: var(--pass); }
    .badge.in_progress { background: #fef0c7; color: #b54708; }
    footer { text-align: center; padding: 2rem; color: var(--muted); font-size: .85rem; }
    a { color: var(--accent); }
  </style>
</head>
<body>
  <header>
    <h1>{{ org_name }} Trust Center</h1>
    <p>Security and compliance posture for partners and customers. HIPAA Security Rule monitoring via open-source controls.</p>
  </header>
  <main>
    <div class="grid">
      <div class="card">
        <div class="score">{{ posture_score }}%</div>
        <div>HIPAA posture score</div>
        <small class="muted">Updated {{ generated_at[:10] }}</small>
      </div>
      <div class="card">
        <strong>{{ summary.pass }}</strong> controls passing<br>
        <small>{{ summary.fail }} failing · {{ summary.warn }} warnings</small>
      </div>
      <div class="card">
        <strong>{{ cert_count }}</strong> certifications listed<br>
        <small>Contact: <a href="mailto:{{ contact_email }}">{{ contact_email }}</a></small>
      </div>
    </div>

    <h2>Certifications & attestations</h2>
    <div class="grid">
      {% for c in certifications %}
      <div class="card">
        <strong>{{ c.name }}</strong><br>
        <span class="badge {{ c.status }}">{{ c.status | replace('_', ' ') }}</span>
        {% if c.report_date %}<br><small>Report date: {{ c.report_date }}</small>{% endif %}
      </div>
      {% else %}
      <p>No public certifications configured. Add <code>compliance/certifications.yaml</code>.</p>
      {% endfor %}
    </div>

    <h2>Security program</h2>
    <ul>
      {% for item in program_items %}
      <li>{{ item }}</li>
      {% endfor %}
    </ul>

    <h2>Policy library</h2>
    <ul>
      {% for p in policies %}
      <li>{{ p }}</li>
      {% endfor %}
    </ul>

    {% if request_access_note %}
    <h2>Request audit evidence</h2>
    <p>{{ request_access_note }}</p>
    {% endif %}
    {% if public_url %}
    <p style="margin-top:1.5rem"><a href="{{ public_url }}">View this page at {{ public_url }}</a></p>
    {% endif %}
  </main>
  <footer>
    {% if public_url %}<p>Public trust center: <a href="{{ public_url }}">{{ public_url }}</a></p>{% endif %}
    Generated by <a href="https://github.com/jdawg555/hipaa-security-test">hipaa-audit</a>. Not a substitute for a signed BAA or formal audit report.
  </footer>
</body>
</html>
"""


def load_certifications(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        return []
    raw = yaml.safe_load(path.read_text()) or {}
    certs = raw.get("certifications", [])
    return [c for c in certs if c.get("public", True)]


def list_policy_names(repo_path: Path, policy_dir: str) -> list[str]:
    policies = repo_path / policy_dir
    if not policies.is_dir():
        return []
    return sorted(p.stem.replace("-", " ").title() for p in policies.glob("*.md"))


def publish_trust_center(
    *,
    repo_path: Path,
    config: dict[str, Any],
    report_json: Path,
) -> Path:
    tc_cfg = config.get("trust_center", {})
    output_dir = repo_path / tc_cfg.get("output_dir", "compliance/trust-center")
    output_dir.mkdir(parents=True, exist_ok=True)

    data = json.loads(report_json.read_text())
    certs_path = repo_path / tc_cfg.get("certifications_path", "compliance/certifications.yaml")
    certifications = load_certifications(certs_path)

    program_items = tc_cfg.get(
        "program_items",
        [
            "Annual Security Risk Assessment (SRA)",
            "Quarterly access reviews for SaaS and cloud IAM",
            "Vendor risk assessments with BAA tracking",
            "Workforce HIPAA training and policy acknowledgments",
            "Continuous AWS/GitHub/identity monitoring",
        ],
    )

    html = Template(TRUST_TEMPLATE).render(
        org_name=data.get("org_name", config.get("org_name", "Organization")),
        generated_at=data.get("generated_at", ""),
        posture_score=data.get("posture", {}).get("score", 0),
        summary=data.get("summary", {}),
        certifications=certifications,
        cert_count=len(certifications),
        contact_email=tc_cfg.get("contact_email", "security@example.com"),
        policies=list_policy_names(repo_path, config.get("policy_dir", "policies")),
        program_items=program_items,
        public_url=tc_cfg.get("public_url", "").strip(),
        request_access_note=tc_cfg.get(
            "request_access_note",
            "Enterprise customers may request our auditor evidence bundle under NDA. Contact the address above.",
        ),
    )
    out = output_dir / "index.html"
    out.write_text(html)
    return out
